console.log("***********************************");
console.log("math properties");
let num=[3,4,7,9,22,55,77,9,0,3]
x=2265.655
console.log(Math.LN10);
console.log(Math.E);
console.log(Math.LN2);
console.log(Math.LOG10E);
console.log(Math.PI);
console.log(Math.SQRT1_2);
console.log(Math.SQRT2);
console.log("math methods");
console.log("abs - absolute");
console.log(Math.abs(x));//abs(x: number): number
console.log(Math.abs(-1));
console.log(Math.abs(null));
console.log(Math.abs(20));
console.log(Math.abs("string"));
console.log("acos -arccosine ");
console.log(Math.acos("string"));
console.log(Math.acos(2));
console.log(Math.acos(null));
console.log(Math.acos(-1));
console.log(Math.acos(x));
console.log("asin -arcsine");
console.log(Math.asin(-1));
console.log(Math.asin(null));
console.log(Math.asin(30));
console.log(Math.asin(1));
console.log(Math.asin("string"));
console.log("atan -arctangent");
console.log(Math.atan(-1));
console.log(Math.atan(.5));
console.log(Math.atan(30));
console.log( Math.atan("string"));
console.log("atan2");
console.log(Math.atan2 ( 30,45 ));
console.log(Math.atan2(90,15));
console.log(Math.atan2(15,90));
console.log( Math.atan2(0, -0));
console.log(Math.atan2(+Infinity, -Infinity));
console.log("ceil");
console.log(Math.ceil(45.95));
console.log(Math.ceil(45.20));
console.log(Math.ceil(-45.95));
console.log(Math.ceil(-45.20));
console.log("cos");
console.log( Math.cos(90));
console.log(Math.cos(30));
console.log(Math.cos(-1));
console.log(Math.cos(2*Math.PI));
console.log("exp");
console.log(Math.exp(1));
console.log(Math.exp(30));
console.log(Math.exp(-1));
console.log(Math.exp(.5));
console.log("floor");
console.log( Math.floor(10.3));
console.log(Math.floor(30.9));
console.log(Math.floor(-2.9));
console.log(Math.floor(-2.2));
console.log("log");
console.log(Math.log(10));
console.log(Math.log(22));
console.log(Math.log(111));
console.log(Math.log(33));
console.log("max");
console.log(Math.max(10, 20, -1, 100));
console.log(Math.max(num));
console.log(Math.max(-1, -3, -40));
console.log(Math.max(100));
console.log("min");
console.log( Math.min(10, 20, -1, 100));
console.log(Math.min(-1, -3, -40));
console.log(Math.min(0, -1));
console.log(Math.min(num));
console.log("power");
console.log(Math.pow(7, 2));
console.log(Math.pow(-7, 2));
console.log(Math.pow(4, 2));
console.log(Math.pow(0, 12));
console.log("random");
console.log(Math.random());
console.log(Math.random(1,2,3,44,55,77,999,88,66));
console.log("round");
console.log(Math.round(20.8));
console.log(Math.round(20.1));
console.log(Math.round(-20.8));
console.log(Math.round(-20.2));
console.log("sin");
console.log(Math.sin( 0.5 ));
console.log(Math.sin( 0 ));
console.log(Math.sin( 1));
console.log(Math.sin( 90));
console.log(Math.sin(30));
console.log(Math.sin(Math.PI/2));
console.log(Math.sin(Math.PI/6));
console.log(Math.sin(Math.PI/8));
console.log(Math.sin(Math.PI/4));
console.log("sqrt");
console.log(Math.sqrt( 0.5 ));
console.log(Math.sqrt(4 ));
console.log(Math.sqrt( 19));
console.log(Math.sqrt( 100));
console.log("tan");
console.log(Math.tan(Math.PI/4 ));
console.log(Math.tan( 30))
console.log(Math.tan( 0 ))
console.log(Math.tan( 90))
console.log(Math.tan( 45))
console.log(Math.tan(1))
// console.log("tosource");
// console.log(Math.toSource ( Math));
console.log("trunc");
console.log(Math.trunc(13.37));
console.log(Math.trunc(42.84));
console.log(Math.trunc(0.123));
console.log(Math.trunc(-0.123));
console.log("tanh");
console.log(Math.tanh(-1));
console.log(Math.tanh(0));
console.log(Math.tanh(Infinity));
console.log(Math.tanh(1));
console.log("sinh");
console.log(Math.sinh(0));
console.log(Math.sinh(1));
console.log(Math.sinh(-1));
console.log(Math.sinh(2));

console.log("**************************************");